# Generated by Django 4.0.3 on 2022-11-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tliublog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tliublog.category', verbose_name='文章分类'),
            preserve_default=False,
        ),
    ]
