# Generated by Django 4.0.3 on 2022-11-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tliublog', '0003_sidebar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['-sort'], 'verbose_name': '侧边栏', 'verbose_name_plural': '侧边栏'},
        ),
    ]
