# Generated by Django 4.0.3 on 2022-11-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tliublog', '0004_alter_sidebar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AddField(
            model_name='article',
            name='pageview',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
